/// Expect:
/// - error: "throw expression does not produce an error"

fn foo() throws -> u32 {
    throw 1
    return 2
}

fn main() {
    let x = foo()
    println("{}", x)
}
